"""
Django settings for VotacionCESA project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
try:
    # If python-dotenv is available, load variables from a local .env file at project root
    from dotenv import load_dotenv
    load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))
except Exception:
    # dotenv is optional in environments where env vars are provided externally
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--_6@p372o7x3q8m$1visovn$3ijj#ita31o0ua6@#-e&46f*n&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'votaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'VotacionCESA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Aquí le decimos que busque en una carpeta 'templates' en la raíz del proyecto
        # y también en la carpeta 'templates' junto a este settings.py (caso de estructuras anidadas)
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(str(Path(__file__).resolve().parent), 'templates'),
        ], 
        'APP_DIRS': True,
        'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
    },
]

WSGI_APPLICATION = 'VotacionCESA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'

# Allow login using control_number via custom backend (falls back to ModelBackend)
AUTHENTICATION_BACKENDS = [
    'votaciones.auth_backends.ControlNumberBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Algorand (optional) - provide values via environment variables in production
# Defaults favor a local Algorand Sandbox (http://localhost:4001) for development.
ALGOD_ADDRESS = os.environ.get('ALGOD_ADDRESS', 'http://localhost:4001')
ALGOD_TOKEN = os.environ.get('ALGOD_TOKEN', '')
# Support PureStake/third-party providers via PURESTAKE_APIKEY env var
ALGOD_HEADERS = None
PURESTAKE_APIKEY = os.environ.get('PURESTAKE_APIKEY')
if PURESTAKE_APIKEY:
    ALGOD_HEADERS = {'X-API-Key': PURESTAKE_APIKEY}

# Application / verification settings
# ALGORAND_APP_ID: app id (smart contract) used for registration checks (string or int)
ALGORAND_APP_ID = os.environ.get('ALGORAND_APP_ID', None)
# Require that voters have a registered blockchain address opted-in to the app (0/1)
REQUIRE_BLOCKCHAIN_REGISTRATION = bool(int(os.environ.get('REQUIRE_BLOCKCHAIN_REGISTRATION', '0')))
# Optional whitelist for addresses (comma-separated) used when DEBUG=True
BLOCKCHAIN_REGISTERED_ADDRESSES = [a.strip() for a in os.environ.get('BLOCKCHAIN_REGISTERED_ADDRESSES', '').split(',') if a.strip()]

# Sender credentials for on-chain txs (use env vars or a secure secret store)
# ALGORAND_SENDER_MNEMONIC is the easiest for local testing; in production use a key vault
ALGORAND_SENDER_MNEMONIC = os.environ.get('ALGORAND_SENDER_MNEMONIC', '')

# Email settings placeholder (configure for real email delivery when needed)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25') or 25)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = bool(os.environ.get('EMAIL_USE_TLS', ''))


# Final values are sourced from environment variables above.
# (Don't override them here so dev/prod envs can control behavior.)
