# Generated by Django 5.2.7 on 2025-11-11 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0002_vote_hash_block_vote_valid_voter_has_voted_election_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onchain_records', to='votaciones.candidate')),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onchain_records', to='votaciones.election')),
            ],
        ),
    ]
