# Generated by Django 5.2.7 on 2025-11-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0004_alter_vote_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='blockchain_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
